PRODUCT_COPY_FILES += \
    vendor/sony/scorpion-blobs/system/etc/acdbdata/Fluid/Fluid_Bluetooth_cal.acdb:system/etc/acdbdata/Fluid/Fluid_Bluetooth_cal.acdb \
    vendor/sony/scorpion-blobs/system/etc/acdbdata/Fluid/Fluid_General_cal.acdb:system/etc/acdbdata/Fluid/Fluid_General_cal.acdb \
    vendor/sony/scorpion-blobs/system/etc/acdbdata/Fluid/Fluid_Global_cal.acdb:system/etc/acdbdata/Fluid/Fluid_Global_cal.acdb \
    vendor/sony/scorpion-blobs/system/etc/acdbdata/Fluid/Fluid_Handset_cal.acdb:system/etc/acdbdata/Fluid/Fluid_Handset_cal.acdb \
    vendor/sony/scorpion-blobs/system/etc/acdbdata/Fluid/Fluid_Hdmi_cal.acdb:system/etc/acdbdata/Fluid/Fluid_Hdmi_cal.acdb \
    vendor/sony/scorpion-blobs/system/etc/acdbdata/Fluid/Fluid_Headset_cal.acdb:system/etc/acdbdata/Fluid/Fluid_Headset_cal.acdb \
    vendor/sony/scorpion-blobs/system/etc/acdbdata/Fluid/Fluid_Speaker_cal.acdb:system/etc/acdbdata/Fluid/Fluid_Speaker_cal.acdb \
    vendor/sony/scorpion-blobs/system/etc/acdbdata/Liquid/Liquid_Bluetooth_cal.acdb:system/etc/acdbdata/Liquid/Liquid_Bluetooth_cal.acdb \
    vendor/sony/scorpion-blobs/system/etc/acdbdata/Liquid/Liquid_General_cal.acdb:system/etc/acdbdata/Liquid/Liquid_General_cal.acdb \
    vendor/sony/scorpion-blobs/system/etc/acdbdata/Liquid/Liquid_Global_cal.acdb:system/etc/acdbdata/Liquid/Liquid_Global_cal.acdb \
    vendor/sony/scorpion-blobs/system/etc/acdbdata/Liquid/Liquid_Handset_cal.acdb:system/etc/acdbdata/Liquid/Liquid_Handset_cal.acdb \
    vendor/sony/scorpion-blobs/system/etc/acdbdata/Liquid/Liquid_Hdmi_cal.acdb:system/etc/acdbdata/Liquid/Liquid_Hdmi_cal.acdb \
    vendor/sony/scorpion-blobs/system/etc/acdbdata/Liquid/Liquid_Headset_cal.acdb:system/etc/acdbdata/Liquid/Liquid_Headset_cal.acdb \
    vendor/sony/scorpion-blobs/system/etc/acdbdata/Liquid/Liquid_Speaker_cal.acdb:system/etc/acdbdata/Liquid/Liquid_Speaker_cal.acdb \
    vendor/sony/scorpion-blobs/system/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:system/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/sony/scorpion-blobs/system/etc/acdbdata/MTP/MTP_General_cal.acdb:system/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/sony/scorpion-blobs/system/etc/acdbdata/MTP/MTP_Global_cal.acdb:system/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/sony/scorpion-blobs/system/etc/acdbdata/MTP/MTP_Handset_cal.acdb:system/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/sony/scorpion-blobs/system/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:system/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/sony/scorpion-blobs/system/etc/acdbdata/MTP/MTP_Headset_cal.acdb:system/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/sony/scorpion-blobs/system/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:system/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/sony/scorpion-blobs/system/etc/audio_platform_info.xml:system/etc/audio_platform_info.xml \
    vendor/sony/scorpion-blobs/system/etc/audio_policy.conf:system/etc/audio_policy.conf \
    vendor/sony/scorpion-blobs/system/etc/firmware/BCM43xx.hcd:system/etc/firmware/BCM43xx.hcd \
    vendor/sony/scorpion-blobs/system/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    vendor/sony/scorpion-blobs/system/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    vendor/sony/scorpion-blobs/system/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    vendor/sony/scorpion-blobs/system/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/sony/scorpion-blobs/system/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/sony/scorpion-blobs/system/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    vendor/sony/scorpion-blobs/system/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    vendor/sony/scorpion-blobs/system/etc/firmware/adsp.b00:system/etc/firmware/adsp.b00 \
    vendor/sony/scorpion-blobs/system/etc/firmware/adsp.b01:system/etc/firmware/adsp.b01 \
    vendor/sony/scorpion-blobs/system/etc/firmware/adsp.b02:system/etc/firmware/adsp.b02 \
    vendor/sony/scorpion-blobs/system/etc/firmware/adsp.b03:system/etc/firmware/adsp.b03 \
    vendor/sony/scorpion-blobs/system/etc/firmware/adsp.b04:system/etc/firmware/adsp.b04 \
    vendor/sony/scorpion-blobs/system/etc/firmware/adsp.b05:system/etc/firmware/adsp.b05 \
    vendor/sony/scorpion-blobs/system/etc/firmware/adsp.b06:system/etc/firmware/adsp.b06 \
    vendor/sony/scorpion-blobs/system/etc/firmware/adsp.b07:system/etc/firmware/adsp.b07 \
    vendor/sony/scorpion-blobs/system/etc/firmware/adsp.b08:system/etc/firmware/adsp.b08 \
    vendor/sony/scorpion-blobs/system/etc/firmware/adsp.b09:system/etc/firmware/adsp.b09 \
    vendor/sony/scorpion-blobs/system/etc/firmware/adsp.b10:system/etc/firmware/adsp.b10 \
    vendor/sony/scorpion-blobs/system/etc/firmware/adsp.b11:system/etc/firmware/adsp.b11 \
    vendor/sony/scorpion-blobs/system/etc/firmware/adsp.b12:system/etc/firmware/adsp.b12 \
    vendor/sony/scorpion-blobs/system/etc/firmware/adsp.mdt:system/etc/firmware/adsp.mdt \
    vendor/sony/scorpion-blobs/system/etc/firmware/cmnlib.b00:system/etc/firmware/cmnlib.b00 \
    vendor/sony/scorpion-blobs/system/etc/firmware/cmnlib.b01:system/etc/firmware/cmnlib.b01 \
    vendor/sony/scorpion-blobs/system/etc/firmware/cmnlib.b02:system/etc/firmware/cmnlib.b02 \
    vendor/sony/scorpion-blobs/system/etc/firmware/cmnlib.b03:system/etc/firmware/cmnlib.b03 \
    vendor/sony/scorpion-blobs/system/etc/firmware/cmnlib.mdt:system/etc/firmware/cmnlib.mdt \
    vendor/sony/scorpion-blobs/system/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/sony/scorpion-blobs/system/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/sony/scorpion-blobs/system/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/sony/scorpion-blobs/system/etc/firmware/mba.b00:system/etc/firmware/mba.b00 \
    vendor/sony/scorpion-blobs/system/etc/firmware/mba.mdt:system/etc/firmware/mba.mdt \
    vendor/sony/scorpion-blobs/system/etc/firmware/modem.b00:system/etc/firmware/modem.b00 \
    vendor/sony/scorpion-blobs/system/etc/firmware/modem.b01:system/etc/firmware/modem.b01 \
    vendor/sony/scorpion-blobs/system/etc/firmware/modem.b02:system/etc/firmware/modem.b02 \
    vendor/sony/scorpion-blobs/system/etc/firmware/modem.b03:system/etc/firmware/modem.b03 \
    vendor/sony/scorpion-blobs/system/etc/firmware/modem.b06:system/etc/firmware/modem.b06 \
    vendor/sony/scorpion-blobs/system/etc/firmware/modem.b08:system/etc/firmware/modem.b08 \
    vendor/sony/scorpion-blobs/system/etc/firmware/modem.b09:system/etc/firmware/modem.b09 \
    vendor/sony/scorpion-blobs/system/etc/firmware/modem.b11:system/etc/firmware/modem.b11 \
    vendor/sony/scorpion-blobs/system/etc/firmware/modem.b12:system/etc/firmware/modem.b12 \
    vendor/sony/scorpion-blobs/system/etc/firmware/modem.b13:system/etc/firmware/modem.b13 \
    vendor/sony/scorpion-blobs/system/etc/firmware/modem.b14:system/etc/firmware/modem.b14 \
    vendor/sony/scorpion-blobs/system/etc/firmware/modem.b15:system/etc/firmware/modem.b15 \
    vendor/sony/scorpion-blobs/system/etc/firmware/modem.b16:system/etc/firmware/modem.b16 \
    vendor/sony/scorpion-blobs/system/etc/firmware/modem.b17:system/etc/firmware/modem.b17 \
    vendor/sony/scorpion-blobs/system/etc/firmware/modem.b18:system/etc/firmware/modem.b18 \
    vendor/sony/scorpion-blobs/system/etc/firmware/modem.b19:system/etc/firmware/modem.b19 \
    vendor/sony/scorpion-blobs/system/etc/firmware/modem.b22:system/etc/firmware/modem.b22 \
    vendor/sony/scorpion-blobs/system/etc/firmware/modem.b23:system/etc/firmware/modem.b23 \
    vendor/sony/scorpion-blobs/system/etc/firmware/modem.b24:system/etc/firmware/modem.b24 \
    vendor/sony/scorpion-blobs/system/etc/firmware/modem.b25:system/etc/firmware/modem.b25 \
    vendor/sony/scorpion-blobs/system/etc/firmware/modem.mdt:system/etc/firmware/modem.mdt \
    vendor/sony/scorpion-blobs/system/etc/firmware/touch_module_id_0x97.img:system/etc/firmware/touch_module_id_0x97.img \
    vendor/sony/scorpion-blobs/system/etc/firmware/touch_module_id_0x98.img:system/etc/firmware/touch_module_id_0x98.img \
    vendor/sony/scorpion-blobs/system/etc/firmware/touch_module_id_0x99.img:system/etc/firmware/touch_module_id_0x99.img \
    vendor/sony/scorpion-blobs/system/etc/firmware/touch_module_id_0x9a.img:system/etc/firmware/touch_module_id_0x9a.img \
    vendor/sony/scorpion-blobs/system/etc/firmware/touch_module_id_0xa4.img:system/etc/firmware/touch_module_id_0xa4.img \
    vendor/sony/scorpion-blobs/system/etc/firmware/touch_module_id_0xa5.img:system/etc/firmware/touch_module_id_0xa5.img \
    vendor/sony/scorpion-blobs/system/etc/firmware/touch_module_id_0xa6.img:system/etc/firmware/touch_module_id_0xa6.img \
    vendor/sony/scorpion-blobs/system/etc/firmware/touch_module_id_0xa7.img:system/etc/firmware/touch_module_id_0xa7.img \
    vendor/sony/scorpion-blobs/system/etc/firmware/touch_module_id_0xa8.img:system/etc/firmware/touch_module_id_0xa8.img \
    vendor/sony/scorpion-blobs/system/etc/firmware/touch_module_id_0xa9.img:system/etc/firmware/touch_module_id_0xa9.img \
    vendor/sony/scorpion-blobs/system/etc/firmware/tzhdcp.b00:system/etc/firmware/tzhdcp.b00 \
    vendor/sony/scorpion-blobs/system/etc/firmware/tzhdcp.b01:system/etc/firmware/tzhdcp.b01 \
    vendor/sony/scorpion-blobs/system/etc/firmware/tzhdcp.b02:system/etc/firmware/tzhdcp.b02 \
    vendor/sony/scorpion-blobs/system/etc/firmware/tzhdcp.b03:system/etc/firmware/tzhdcp.b03 \
    vendor/sony/scorpion-blobs/system/etc/firmware/tzhdcp.mdt:system/etc/firmware/tzhdcp.mdt \
    vendor/sony/scorpion-blobs/system/etc/firmware/tzlibasb.b00:system/etc/firmware/tzlibasb.b00 \
    vendor/sony/scorpion-blobs/system/etc/firmware/tzlibasb.b01:system/etc/firmware/tzlibasb.b01 \
    vendor/sony/scorpion-blobs/system/etc/firmware/tzlibasb.b02:system/etc/firmware/tzlibasb.b02 \
    vendor/sony/scorpion-blobs/system/etc/firmware/tzlibasb.b03:system/etc/firmware/tzlibasb.b03 \
    vendor/sony/scorpion-blobs/system/etc/firmware/tzlibasb.mdt:system/etc/firmware/tzlibasb.mdt \
    vendor/sony/scorpion-blobs/system/etc/firmware/tznautilus.b00:system/etc/firmware/tznautilus.b00 \
    vendor/sony/scorpion-blobs/system/etc/firmware/tznautilus.b01:system/etc/firmware/tznautilus.b01 \
    vendor/sony/scorpion-blobs/system/etc/firmware/tznautilus.b02:system/etc/firmware/tznautilus.b02 \
    vendor/sony/scorpion-blobs/system/etc/firmware/tznautilus.b03:system/etc/firmware/tznautilus.b03 \
    vendor/sony/scorpion-blobs/system/etc/firmware/tznautilus.mdt:system/etc/firmware/tznautilus.mdt \
    vendor/sony/scorpion-blobs/system/etc/firmware/tzsuntory.b00:system/etc/firmware/tzsuntory.b00 \
    vendor/sony/scorpion-blobs/system/etc/firmware/tzsuntory.b01:system/etc/firmware/tzsuntory.b01 \
    vendor/sony/scorpion-blobs/system/etc/firmware/tzsuntory.b02:system/etc/firmware/tzsuntory.b02 \
    vendor/sony/scorpion-blobs/system/etc/firmware/tzsuntory.b03:system/etc/firmware/tzsuntory.b03 \
    vendor/sony/scorpion-blobs/system/etc/firmware/tzsuntory.mdt:system/etc/firmware/tzsuntory.mdt \
    vendor/sony/scorpion-blobs/system/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/sony/scorpion-blobs/system/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/sony/scorpion-blobs/system/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/sony/scorpion-blobs/system/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/sony/scorpion-blobs/system/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/sony/scorpion-blobs/system/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/sony/scorpion-blobs/system/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
    vendor/sony/scorpion-blobs/system/etc/firmware/wlan/bcmdhd/bcmdhd.cal:system/etc/firmware/wlan/bcmdhd/bcmdhd.cal \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/FMSpeaker_btm.eq:system/etc/tfa98xx/FMSpeaker_btm.eq \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/FMSpeaker_btm.preset:system/etc/tfa98xx/FMSpeaker_btm.preset \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/FMSpeaker_top.eq:system/etc/tfa98xx/FMSpeaker_top.eq \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/FMSpeaker_top.preset:system/etc/tfa98xx/FMSpeaker_top.preset \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/HiFiSpeakerRing_btm.eq:system/etc/tfa98xx/HiFiSpeakerRing_btm.eq \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/HiFiSpeakerRing_btm.preset:system/etc/tfa98xx/HiFiSpeakerRing_btm.preset \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/HiFiSpeakerRing_top.eq:system/etc/tfa98xx/HiFiSpeakerRing_top.eq \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/HiFiSpeakerRing_top.preset:system/etc/tfa98xx/HiFiSpeakerRing_top.preset \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/HiFiSpeakerSforce_btm.eq:system/etc/tfa98xx/HiFiSpeakerSforce_btm.eq \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/HiFiSpeakerSforce_btm.preset:system/etc/tfa98xx/HiFiSpeakerSforce_btm.preset \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/HiFiSpeakerSforce_top.eq:system/etc/tfa98xx/HiFiSpeakerSforce_top.eq \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/HiFiSpeakerSforce_top.preset:system/etc/tfa98xx/HiFiSpeakerSforce_top.preset \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/HiFiSpeaker_btm.eq:system/etc/tfa98xx/HiFiSpeaker_btm.eq \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/HiFiSpeaker_btm.preset:system/etc/tfa98xx/HiFiSpeaker_btm.preset \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/HiFiSpeaker_top.eq:system/etc/tfa98xx/HiFiSpeaker_top.eq \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/HiFiSpeaker_top.preset:system/etc/tfa98xx/HiFiSpeaker_top.preset \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/TFA9890.patch:system/etc/tfa98xx/TFA9890.patch \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/TFA9890_Receiver.config:system/etc/tfa98xx/TFA9890_Receiver.config \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/TFA9890_btm.config:system/etc/tfa98xx/TFA9890_btm.config \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/TFA9890_top.config:system/etc/tfa98xx/TFA9890_top.config \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/VoiceCallEarpice_top.eq:system/etc/tfa98xx/VoiceCallEarpice_top.eq \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/VoiceCallEarpice_top.preset:system/etc/tfa98xx/VoiceCallEarpice_top.preset \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/VoiceCallSpeaker_btm.eq:system/etc/tfa98xx/VoiceCallSpeaker_btm.eq \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/VoiceCallSpeaker_btm.preset:system/etc/tfa98xx/VoiceCallSpeaker_btm.preset \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/VoiceCallSpeaker_top.eq:system/etc/tfa98xx/VoiceCallSpeaker_top.eq \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/VoiceCallSpeaker_top.preset:system/etc/tfa98xx/VoiceCallSpeaker_top.preset \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/btm.speaker:system/etc/tfa98xx/btm.speaker \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/coldboot.patch:system/etc/tfa98xx/coldboot.patch \
    vendor/sony/scorpion-blobs/system/etc/tfa98xx/top.speaker:system/etc/tfa98xx/top.speaker \
    vendor/sony/scorpion-blobs/system/lib/modules/bcmdhd.ko:system/lib/modules/bcmdhd.ko \
    vendor/sony/scorpion-blobs/system/vendor/firmware/fw_bcmdhd.bin:system/vendor/firmware/fw_bcmdhd.bin \
    vendor/sony/scorpion-blobs/system/vendor/firmware/fw_bcmdhd_apsta.bin:system/vendor/firmware/fw_bcmdhd_apsta.bin \
    vendor/sony/scorpion-blobs/system/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/sony/scorpion-blobs/system/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/sony/scorpion-blobs/system/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/sony/scorpion-blobs/system/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/sony/scorpion-blobs/system/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/sony/scorpion-blobs/system/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/sony/scorpion-blobs/system/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/sony/scorpion-blobs/system/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/sony/scorpion-blobs/system/vendor/lib/libOpenVG.so:system/vendor/lib/libOpenVG.so \
    vendor/sony/scorpion-blobs/system/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/sony/scorpion-blobs/system/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/sony/scorpion-blobs/system/vendor/lib/libc2d2_z180.so:system/vendor/lib/libc2d2_z180.so \
    vendor/sony/scorpion-blobs/system/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/sony/scorpion-blobs/system/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    vendor/sony/scorpion-blobs/system/vendor/lib/libc2d30.so:system/vendor/lib/libc2d30.so \
    vendor/sony/scorpion-blobs/system/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/sony/scorpion-blobs/system/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/sony/scorpion-blobs/system/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/sony/scorpion-blobs/system/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/sony/scorpion-blobs/system/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
    vendor/sony/scorpion-blobs/system/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \

